### ISSUE TITLE
按照README.md中2.2.2的代码来写，会直接报错

### ISSUE THREAD

**Issue by xdlStrive** [pengqiangsheng/easy-typer-js#2]
因为2.2.2的例子中obj的参数只有output，其他参数都被省略了。然而实际代码运行中会检测obj的参数个数，如果不把参数写全，就会报【配置对象错误: 字段数量不正确！】的错误，少写一个都不行...
    然而在文档中并没有提到这一点，只是说obj的参数一定要有且格式要对，希望能补全关于这个的说明，
或者修改代码，给未提供的参数一个默认值也好←_←

**Comment by xdlStrive** [comment]
另外希望能把文本后闪烁光标整合进插件里就更好了，例子中是通过stylus写样式来实现的，但我又不想为了一个光标再加一个依赖...

**Comment by pengqiangsheng** [comment]
ok，文档会修改的，光标样式我后面看看怎么改好。
