### ISSUE TITLE
wiki里2.3=>[2.3.3 原生实例] 代码有问题

### ISSUE THREAD

**Issue by Lantern-r** [pengqiangsheng/easy-typer-js#4]
1. 中文冒号
![image](https://user-images.githubusercontent.com/64698811/147232047-2dd80d84-727b-45d3-92d3-6d77aaabb1a0.png)
2. 少个小括号
![image](https://user-images.githubusercontent.com/64698811/147234462-5536f7ef-b0f8-4774-8c33-6eeddf189ec7.png)

**Comment by pengqiangsheng** [comment]
近期修改，掘金和这里已改好了，就差博客了。
