### ISSUE TITLE
文档错误

### ISSUE THREAD

**Issue by qsyyke** [pengqiangsheng/easy-typer-js#6]
![image](https://user-images.githubusercontent.com/69463896/150974664-f539fe55-f9ae-4d0d-869f-1fb8e226ddfe.png)

大佬，文档这里使用了中文冒号了

[网页链接](https://redqueen.gitee.io/typer/#_2-3-%E5%AE%9E%E6%88%98-%E5%AE%9E%E8%B7%B5%E5%87%BA%E7%9C%9F%E7%90%86-%E5%AE%8C%E6%95%B4%E4%BB%A3%E7%A0%81)

**Comment by pengqiangsheng** [comment]
ok。近期改掉
